# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: kubot-software

  remotes:
    - name: zephyrproject-rtos
      url-base: git@github.com:kpochwala

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true
