# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: kubot-software

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/kpochwala

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-whitelist:
          - cmsis
          - fatfs
          - hal_st
          - hal_stm32
          - zscilib
