name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: app

      - name: Initialize
        working-directory: app
        env: # Or as an environment variable
          key: ${{ secrets.privateKey }}
        run: |
          mkdir -p ~/.ssh/
          echo ${key} > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -T 240 github.com >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no git@github.com

          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build firmware
        working-directory: app
        run: |
          west build -b kubot_f765vi -s app

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: app/build/zephyr/zephyr.*
