name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: app

      - name: Initialize
        working-directory: example-application
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt
          ssh-keyscan -T 240 github.com >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no git@github.com

      - name: Build firmware
        working-directory: example-application
        run: |
          west build -b kubot_f765vi -s app

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: example-application/build/zephyr/zephyr.*
